name: powersync_fuzz
description: A command-line application to fuzz PowerSync disconnect()/connect API.
version: 0.0.1
repository: https://github.com/nurturenature/jepsen-powersync/powersync_fuzz

environment:
  sdk: ^3.6.1

dependencies:
  args: ^2.4.2
  http: ^1.3.0
  jose: ^0.3.4
  list_utilities: ^1.0.0
  logging: ^1.2.0
  postgres: ^3.4.8
  powersync: ^1.11.2

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.14
