services:
  setup:
    depends_on:
      powersync:
        condition: service_healthy

  pg-db:
    networks:
      - jepsen

  mongo:
    networks:
      - jepsen
  mongo-rs-init:
    networks:
      - jepsen

  powersync:
    networks:
      - jepsen

  control:
    image: powersync-control

  n1:
    image: powersync-node
  n2:
    image: powersync-node
  n3:
    image: powersync-node
  n4:
    image: powersync-node
  n5:
    image: powersync-node
  n6:
    image: powersync-node
