services:
  pg-db:
    container_name: pg-db
    hostname: pg-db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${PG_DATABASE_USER}
      - POSTGRES_DB=${PG_DATABASE_NAME}
      - POSTGRES_PASSWORD=${PG_DATABASE_PASSWORD}
      - PGPORT=${PG_DATABASE_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ../init-scripts:/docker-entrypoint-initdb.d
    ports:
      - ${PG_DATABASE_PORT}:${PG_DATABASE_PORT}
    command:
      [
        "postgres",
        "-c",
        "wal_level=logical",
        "-c",
        "log_statement=${PG_LOG_STATEMENT}",
      ]
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${PG_DATABASE_USER} -d ${PG_DATABASE_NAME}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
