name: powersync-fuzz

networks:
  powersync-fuzz:

services:
  powersync-fuzz-node:
    image: powersync-fuzz-node
    container_name: powersync-fuzz-node
    hostname: powersync-fuzz-node
    tty: true
    stop_signal: SIGRTMIN+3
    networks:
      - powersync-fuzz
    depends_on:
      powersync:
        condition: service_started

  pg-db:
    networks:
      - powersync-fuzz

  mongo:
    networks:
      - powersync-fuzz
  mongo-rs-init:
    networks:
      - powersync-fuzz

  powersync:
    networks:
      - powersync-fuzz
