name: powersync-fuzz

x-defaults: &defaults
  privileged: true
  cap_add:
    - ALL
  cgroup: host
  tty: true
  stop_signal: SIGRTMIN+3
  tmpfs:
    - /run:size=100M
    - /run/lock:size=100M
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:rw
    - jepsen-shared:/var/jepsen/shared
  networks:
    - powersync-fuzz
  healthcheck:
    test: ["CMD-SHELL", "systemctl", "is-system-running"]
    interval: 1s
    timeout: 1s
    start_period: 1s
    start_interval: 1s
    retries: 10

x-node: &default-node
  <<: *defaults
  image: powersync-fuzz-node
  depends_on:
    setup:
      condition: service_completed_successfully

volumes:
  jepsen-shared:

networks:
  powersync-fuzz:

services:
  pg-db:
    networks:
      - powersync-fuzz

  mongo:
    networks:
      - powersync-fuzz
  mongo-rs-init:
    networks:
      - powersync-fuzz

  powersync:
    networks:
      - powersync-fuzz

  setup:
    <<: *defaults
    image: ${JEPSEN_REGISTRY:-}jepsen-setup
    container_name: jepsen-setup
    hostname: setup
    entrypoint: ["/usr/local/bin/jepsen-setup.sh"]
    depends_on:
      powersync:
        condition: service_healthy

  powersync-fuzz-node:
    <<: *default-node
    container_name: powersync-fuzz-node
    hostname: powersync-fuzz-node
