name: sqlite3_endpoint
description: A Jepsen endpoint backend by SQLite3.
version: 0.0.1
repository: https://github.com/nurturenature/jepsen-powersync

environment:
  sdk: ^3.4.3

dependencies:
  dotenv: ^4.2.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  sqlite_async: ^0.6.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
