name: sqlite3_endpoint
description: A Jepsen endpoint backend by SQLite3.
version: 0.0.1
repository: https://github.com/nurturenature/jepsen-powersync

environment:
  sdk: ^3.6.1

dependencies:
  dotenv: ^4.2.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  sqlite_async: ^0.11.2

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.14
