name: prop_test
description: Runs individual user sessions, workers, in Isolates.
version: 0.0.1
repository: https://github.com/nurturenature/jepsen-powersync

environment:
  sdk: ^3.4.3

dependencies:
  args: ^2.4.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
