name: atomic-matrix

on:
  workflow_dispatch:

jobs:
  atomic-matrix:
    uses: nurturenature/jepsen-powersync/.github/workflows/run-jepsen-tests.yml@main
    with:
      workloads: >
        [ 'ps-ro-pg-wo', 'ps-wo-pg-ro' ]
      nemeses: >
        [ 'none' ]
      rates: >
        [ '10', '20', '30' ]
      time-limits: >
        ['30', '60', '100' ]
      cli-opts: >
        '--nodes n1,n2 --postgres-nodes n1'
