name: convergence+-matrix

on:
  workflow_dispatch:

jobs:
  convergence:
    uses: nurturenature/jepsen-powersync/.github/workflows/run-jepsen-tests.yml@main
    with:
      workloads: >
        [ 'convergence+' ]
