name: disconnect-connect-matrix

on:
  workflow_dispatch:

jobs:
  disconnect-connect-matrix:
    uses: nurturenature/jepsen-powersync/.github/workflows/run-jepsen-tests.yml@main
    with:
      nemeses: >
        [ 'disconnect-connect,upload-queue' ]
