name: fuzz-no-fault

on:
  workflow_dispatch:

jobs:
  fuzz-no-fault:
    uses: nurturenature/jepsen-powersync/.github/workflows/fuzz-test-runner.yml@main
    with:
      clients: >
        [ '5', '10']
      rates: >
        [ '10', '20', '30', '40', '50']
      times: >
        [ '100', '200', '300', '400', '500', '600', '700', '800', '900', '1000', '1100', '1200' ]
      postgresql: >
        [ '--postgresql', '--no-postgresql' ]
      disconnect: >
        [ '--no-disconnect' ]
      stop-or-kill: >
        [ '--no-stop' ]
      partition: >
        [ '--no-partition' ]
      pause: >
        [ '--no-pause' ]
      cli-opts: >
        [ '' ]
      args: >
        "{'repeat': [ '1' ], 'timeout-minutes': 21}"
