name: fuzz-multi-fault

on:
  workflow_dispatch:

jobs:
  fuzz-multi-fault:
    uses: nurturenature/jepsen-powersync/.github/workflows/run-powersync-fuzz-tests.yml@main
    with:
      clients: >
        [ '5', '10']
      rates: >
        [ '10', '20', '30' ]
      times: >
        [ '100', '200', '300' ]
      postgresql: >
        [ '--postgresql' ]
      disconnect: >
        [ '--disconnect' ]
      partition: >
        [ '--partition' ]
      interval: >
        [ '3', '5' ]
      repeat: >
        [ '1', '2', '3', '4', '5', '6', '7' ]
