name: fuzz-non-monotonic-reads

on:
  workflow_dispatch:

jobs:
  fuzz-non-monotonic-reads:
    uses: nurturenature/jepsen-powersync/.github/workflows/fuzz-test-runner.yml@main
    with:
      postgresql: >
        [ '--postgresql' ]
      disconnect: >
        [ '--disconnect' ]
      partition: >
        [ '--no-partition' ]
      interval: >
        [ '3', '5' ]
      repeat: >
        [ '1', '2', '3', '4' ]
