name: fuzz-disconnect

on:
  workflow_dispatch:

jobs:
  fuzz-disconnect:
    uses: nurturenature/jepsen-powersync/.github/workflows/fuzz-test-runner.yml@main
    with:
      clients: >
        [ '5', '10' ]
      rates: >
        [ '10', '20', '30', '40' ]
      times: >
        [ '100', '200', '300' ]
      postgresql: >
        [ '--postgresql', '--no-postgresql' ]
      disconnect: >
        [ '--disconnect' ]
      partition: >
        [ '--no-partition' ]
      interval: >
        [ '3', '5' ]
      repeat: >
        [ '1', '2' ]
