name: fuzz-non-monotonic-reads

on:
  workflow_dispatch:

jobs:
  fuzz-non-monotonic-reads:
    uses: nurturenature/jepsen-powersync/.github/workflows/fuzz-test-runner.yml@main
    with:
      clients: >
        [ '5', '10']
      rates: >
        [ '10', '20' ]
      times: >
        [ '100', '200', '300' ]
      postgresql: >
        [ '--no-postgresql', '--postgresql' ]
      disconnect: >
        [ '--disconnect' ]
      stop-or-kill: >
        [ '--no-stop' ]
      partition: >
        [ '--partition' ]
      pause: >
        [ '--no-pause' ]
      cli-opts: >
        [ '' ]
      args: >
        "{'repeat': [ '1', '2', '3', '4', '5', '6', '7', '8', '9', '10' ], 'timeout-minutes': 10}
