name: fuzz-exit-code-10

on:
  workflow_dispatch:

jobs:
  fuzz-exit-code-10:
    uses: nurturenature/jepsen-powersync/.github/workflows/run-powersync-fuzz-tests.yml@main
    with:
      clients: >
        [ '5', '10' ]
      rates: >
        [ '30', '40' ]
      times: >
        [ '100', '200' ]
      postgresql: >
        [ '--postgresql' ]
      disconnect: >
        [ '--disconnect' ]
      interval: >
        [ '3', '5' ]
      repeat: >
        [        '1',  '2',  '3',  '4',  '5', '6', '7', '8', '9',
          '10', '11', '12', '13', '14', '15' ]
      timeout-minutes: 5
