name: jepsen-convergence-only

on:
  workflow_dispatch:

jobs:
  jepsen-convergence-only:
    uses: nurturenature/jepsen-powersync/.github/workflows/jepsen-test-runner.yml@main
    with:
      workloads: >
        [ 'convergence' ]
