name: Jepsen Tests Runner

on:
  workflow_dispatch:
    inputs:
      workloads:
        description: Workloads (as JSON)
        type: string
        required: true
        default: "[ 'ps-rw-pg-rw' ]"
      nemeses:
        description: 'Nemeses (as JSON)'
        type: string
        required: true
        default: "[ 'upload-queue' ]"
      rates:
        description: 'Rates (as JSON)'
        type: string
        required: true
        default: "[ '10', '20', '30', '40', '50' ]"
      time-limits:
        description: 'Time limits (as JSON)'
        type: string
        required: true
        default: "[ '100', '200', '300' ]"
      cli-opts:
        description: 'CLI opts string'
        type: string
        required: true
        default: --nodes n1,n2,n3,n4,n5,n6,n7,n8,n9,n10,n11 --postgres-nodes n11
      args:
        description: 'A JSON Map of args (workaround GitHub max inputs)'
        type: string
        required: true
        default: "{'repeat': [ '1' ], 'timeout-minutes': 10, 'powersync-image-tag': 'latest'}"
       
  workflow_call:
    inputs:
      workloads:
        description: 'Workloads (as JSON)'
        type: string
        required: false
        default: "[ 'ps-rw-pg-rw' ]"
      nemeses:
        description: 'Nemeses (as JSON)'
        type: string
        required: false
        default: "[ 'upload-queue' ]"
      rates:
        description: 'Rates (as JSON)'
        type: string
        required: false
        default: "[ '10', '20', '30', '40', '50' ]"
      time-limits:
        description: 'Time limits (as JSON)'
        type: string
        required: false
        default: "[ '100', '200', '300' ]"
      cli-opts:
        description: 'CLI opts string'
        type: string
        required: false
        default: --nodes n1,n2,n3,n4,n5,n6,n7,n8,n9,n10,n11 --postgres-nodes n11
      args:
        description: 'A JSON Map of args (workaround GitHub max inputs)'
        type: string
        required: false
        default: "{'repeat': [ '1' ], 'timeout-minutes': 10, 'powersync-image-tag': 'latest'}"

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        workload:   ${{ fromJSON(inputs.workloads) }}
        nemesis:    ${{ fromJSON(inputs.nemeses) }}
        rate:       ${{ fromJSON(inputs.rates) }}
        time-limit: ${{ fromJSON(inputs.time-limits) }}
        repeat:     ${{ fromJSON(inputs.args).repeat }}

    env:
      test-title: ${{ matrix.rate }}tps-${{ matrix.time-limit }}s-${{ matrix.workload }}-${{ matrix.nemesis }}-${{ matrix.repeat }}
      POWERSYNC_IMAGE_TAG: ${{ fromJSON(inputs.args).powersync-image-tag }}

    steps:  
      - name: Checkout jepsen-powersync
        uses: actions/checkout@v4
      
      - name: Bring Up Docker Environment
        run: |
          cd $GITHUB_WORKSPACE/docker
          ./docker-build.sh      || $(exit 255)
          ./docker-compose-up.sh || $(exit 255)

      - name: Confirm Docker Environment
        run: |
          docker logs jepsen-control &> /dev/null || $(exit 255)
  
      - name: ${{ env.test-title }}
        timeout-minutes: ${{ fromJSON(inputs.args).timeout-minutes }}
        run: |
          cd $GITHUB_WORKSPACE/docker
          ./docker-run.sh lein run test --workload          ${{ matrix.workload }} \
                                        --nemesis           ${{ matrix.nemesis }}  \
                                        --rate              ${{ matrix.rate }}     \
                                        --time-limit        ${{ matrix.time-limit }} \
                                        ${{ inputs.cli-opts }}

      - name: Jepsen, PowerSync, and PostgreSQL Logs
        if: ${{ always() }}
        run: |
          mkdir -p $GITHUB_WORKSPACE/store/current
          docker logs powersync     &> $GITHUB_WORKSPACE/store/current/powersync.log     || echo "no docker logs" > $GITHUB_WORKSPACE/store/current/powersync.log
          docker logs pg-db         &> $GITHUB_WORKSPACE/store/current/pg-db.log         || echo "no docker logs" > $GITHUB_WORKSPACE/store/current/pg-db.log
          docker logs mongo         &> $GITHUB_WORKSPACE/store/current/mongo.log         || echo "no docker logs" > $GITHUB_WORKSPACE/store/current/mongo.log
          docker logs mongo-rs-init &> $GITHUB_WORKSPACE/store/current/mongo-rs-init.log || echo "no docker logs" > $GITHUB_WORKSPACE/store/current/mongo-rs-init.log
          docker cp jepsen-control:/jepsen/jepsen-powersync/store/current/. $GITHUB_WORKSPACE/store/current \
            || echo "no jepsen-control store" > $GITHUB_WORKSPACE/store/current/jepsen-control.log
          tail -n 100 $GITHUB_WORKSPACE/store/current/jepsen.log > $GITHUB_WORKSPACE/store/current/tail-jepsen.log \
            || echo "no jepsen.log" > $GITHUB_WORKSPACE/store/current/tail-jepsen.log

      - name: 'Jepsen Test Artifacts: summary'
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: '${{ env.test-title }}-summary'
          path: |
            ${{ github.workspace }}/store/current/results.edn
            ${{ github.workspace }}/store/current/tail-jepsen.log
            
      - name: 'Jepsen Test Artifacts: full'
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: '${{ env.test-title }}-${{ job.status }}'
          path: |
            ${{ github.workspace }}/store/current
