name: jepsen-ps-rw-pg-ro

on:
  workflow_dispatch:

jobs:
  jepsen-ps-rw-pg-ro:
    uses: nurturenature/jepsen-powersync/.github/workflows/jepsen-test-runner.yml@main
    with:
      workloads: >
        [ 'ps-rw-pg-ro' ]
