name: partition-matrix

on:
  workflow_dispatch:

jobs:
  partition-matrix:
    uses: nurturenature/jepsen-powersync/.github/workflows/run-jepsen-tests.yml@main
    with:
      nemeses: >
        [ 'partition-sync' ]
