name: ps-single

on:
  workflow_dispatch:

jobs:
  ps-single:
    uses: nurturenature/jepsen-powersync/.github/workflows/run-jepsen-tests.yml@main
    with:
      workloads: >
        [ 'powersync-single' ]
      nemeses: >
        [ 'none' ]
      rates: >
        [ '150' ]
      time-limits: >
        ['100' ]
      cli-opts: >
        '--nodes n1'
