name: ps-rw-pg-ro-matrix

on:
  workflow_dispatch:

jobs:
  ps-rw-pg-ro-matrix:
    uses: nurturenature/jepsen-powersync/.github/workflows/run-jepsen-tests.yml@main
    with:
      workloads: >
        [ 'ps-rw-pg-ro' ]
      backend-connectors: >
        [ 'CrudTransactionConnector']
      nemeses: >
        [ 'none' ]
      rates: >
        [ '10', '20', '30', '40', '50' ]
      time-limits: >
        ['100', '200', '300', '400', '500', '600' ]
      cli-opts: >
        '--nodes n1,n2,n3,n4,n5 --postgres-nodes n1'
