name: sqlite3-local

on:
  workflow_dispatch:

jobs:
  sqlite3-local:
    runs-on: ubuntu-latest

    env:
      test-title: sqlite3-local-150tps-100s

    steps:  
      - name: Checkout jepsen-powersync
        uses: actions/checkout@v4
      
      - name: Bring Up Docker Environment
        run: |
          cd $GITHUB_WORKSPACE/docker
          docker build \
                 -t powersync-node \
                 --build-arg JEPSEN_REGISTRY="ghcr.io/nurturenature/jepsen-docker/" \
                 -f jepsen-node.Dockerfile \
                 ../sqlite3_endpoint
          docker build \
                 -t powersync-control \
                 --build-arg JEPSEN_REGISTRY="ghcr.io/nurturenature/jepsen-docker/" \
                 -f jepsen-control.Dockerfile \
                 ../jepsen
          docker compose \
                 -f jepsen-compose.yaml \
                 --env-file ../.env \
                 up \
                 --detach \
                 --wait
          docker ps --format="table {{.Names}}\t{{.Image}}\t{{.Status}}"
          
      - name: ${{ env.test-title }}
        run: |
          cd $GITHUB_WORKSPACE/docker
          ./docker-run.sh lein run test --workload   sqlite3-local \
                                        --nemesis    none \
                                        --rate       150 \
                                        --time-limit 100 \
                                        --nodes      n1

      - name: Jepsen Logs
        if: ${{ always() }}
        run: |
          mkdir -p $GITHUB_WORKSPACE/store/current
          docker cp jepsen-control:/jepsen/jepsen-powersync/store/current/. $GITHUB_WORKSPACE/store/current
          tail -n 100 $GITHUB_WORKSPACE/store/current/jepsen.log > $GITHUB_WORKSPACE/store/current/tail-jepsen.log

      - name: 'Jepsen Test Artifacts: summary'
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: '${{ env.test-title }}-summary'
          path: |
            ${{ github.workspace }}/store/current/results.edn
            ${{ github.workspace }}/store/current/tail-jepsen.log
            
      - name: 'Jepsen Test Artifacts: failure-full'
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: '${{ env.test-title }}-failure-full'
          path: |
            ${{ github.workspace }}/store/current
